name = "measurement"
version = "0.1.0"
defaultTargets = ["Measurement"]

[[lean_lib]]
name = "Measurement"
srcDir = "."

[[lean_lib]]
name = "Experiments"
srcDir = "."

[package]
name = "measurement"

moreLeanArgs = [
  "-DautoImplicit=false"
]
