import Measurement.Episode16

/-!
# Epiphany formalization wrapper — Stage 1 (pivoted)

A thin formal layer above the typeclass cascade in `Episode1.lean` through
`Episode16.lean`. The episodes are the artifact; this file proves things
*about* the artifact.

## After the pivot

The original first draft treated the 36 gates as a finite Boolean coordinate
basis (`Bool^36`). Per the second round of review, that frame is wrong: the
gates are **serial formation stages** in a BNF/Herbrand-style production
grammar, not independent coordinates.

This file keeps the artifacts that survive the pivot:

- `Gate` — the 36 typeclass-bearing primitives.
- `Gate.all` — ordered enumeration (order is now load-bearing).
- `Gate.all_length` — the count theorem.
- `FullCascadeObject` — bundled cascade evidence.
- `truthObject` — canonical realized cascade at `Prop` / `truthCarrier`.
- `Stage` — the 37-element serial stage type (`fact` + 36 gates).

The Boolean profile machinery (`GateProfile`, `probe`, etc.) is moved to
`ProfileToy.lean` and marked as a sidelined diagnostic model. The main
serial-grammar formalization lives in:

- `Grammar.lean`  — `Step`, `Derivation`, `inferred_derivable`
- `Cost.lean`     — structural cost on derivations
- `Herbrand.lean` — symbolic term universe generated by the grammar
- `Irredundance.lean` — derivability/cost irredundance
- `Minimality.lean`   — final wrapper theorem
-/

namespace Measurement.Formalization

universe i

/-! ## The `Gate` type

The 36 primitive typeclass-bearing gates of the cascade, in serial
dependency order from `DISTINGUISHABLE` through `INFERRED`. The ordering is
load-bearing: it is the serial grammar's production order. -/

/-- The 36 primitive measurement gates. -/
inductive Gate
  | distinguishable
  | admissible
  | countable
  | encoded
  | residue
  | binary
  | repeatable
  | numeric
  | representable
  | physical
  | comparable
  | observed
  | present
  | measurable
  | gungan
  | source
  | executed
  | value
  | magnitude
  | scaled
  | load
  | finiteElephant
  | bullshit
  | propaganda
  | acolyte
  | scientific
  | truth
  | witnessed
  | real
  | «local»
  | universal
  | logical
  | halted
  | measured
  | compiled
  | inferred
  deriving DecidableEq, Repr

namespace Gate

/-- The complete enumeration of gates, in serial dependency order. -/
def all : List Gate :=
  [ .distinguishable, .admissible, .countable, .encoded, .residue, .binary
  , .repeatable, .numeric, .representable, .physical, .comparable, .observed
  , .present, .measurable, .gungan, .source, .executed, .value, .magnitude
  , .scaled, .load, .finiteElephant, .bullshit, .propaganda, .acolyte
  , .scientific, .truth, .witnessed, .real, .«local», .universal, .logical
  , .halted, .measured, .compiled, .inferred
  ]

/-- 36 is a theorem, not a count. -/
theorem all_length : Gate.all.length = 36 := by decide

end Gate

/-! ## The `Stage` type

A `Stage` is either the foundational `fact` or one of the 36 gates. Stages
carry the serial grammar: derivations begin at `.fact` and progress through
each stage in order, ending at `.inferred`. -/

/-- The 37 serial formation stages: `fact` plus the 36 gates. -/
inductive Stage
  | fact
  | distinguishable
  | admissible
  | countable
  | encoded
  | residue
  | binary
  | repeatable
  | numeric
  | representable
  | physical
  | comparable
  | observed
  | present
  | measurable
  | gungan
  | source
  | executed
  | value
  | magnitude
  | scaled
  | load
  | finiteElephant
  | bullshit
  | propaganda
  | acolyte
  | scientific
  | truth
  | witnessed
  | real
  | «local»
  | universal
  | logical
  | halted
  | measured
  | compiled
  | inferred
  deriving DecidableEq, Repr

namespace Stage

/-- The complete enumeration of stages, in serial grammar order. -/
def all : List Stage :=
  [ .fact, .distinguishable, .admissible, .countable, .encoded, .residue
  , .binary, .repeatable, .numeric, .representable, .physical, .comparable
  , .observed, .present, .measurable, .gungan, .source, .executed, .value
  , .magnitude, .scaled, .load, .finiteElephant, .bullshit, .propaganda
  , .acolyte, .scientific, .truth, .witnessed, .real, .«local», .universal
  , .logical, .halted, .measured, .compiled, .inferred
  ]

/-- 37 stages: `fact` plus 36 gates. -/
theorem all_length : Stage.all.length = 37 := by decide

/-- The immediate successor of a stage in the serial grammar, or `none` at
the terminal stage `.inferred`. This is the BNF spine. -/
def next : Stage → Option Stage
  | .fact            => some .distinguishable
  | .distinguishable => some .admissible
  | .admissible      => some .countable
  | .countable       => some .encoded
  | .encoded         => some .residue
  | .residue         => some .binary
  | .binary          => some .repeatable
  | .repeatable      => some .numeric
  | .numeric         => some .representable
  | .representable   => some .physical
  | .physical        => some .comparable
  | .comparable      => some .observed
  | .observed        => some .present
  | .present         => some .measurable
  | .measurable      => some .gungan
  | .gungan          => some .source
  | .source          => some .executed
  | .executed        => some .value
  | .value           => some .magnitude
  | .magnitude       => some .scaled
  | .scaled          => some .load
  | .load            => some .finiteElephant
  | .finiteElephant  => some .bullshit
  | .bullshit        => some .propaganda
  | .propaganda      => some .acolyte
  | .acolyte         => some .scientific
  | .scientific      => some .truth
  | .truth           => some .witnessed
  | .witnessed       => some .real
  | .real            => some .«local»
  | .«local»         => some .universal
  | .universal       => some .logical
  | .logical         => some .halted
  | .halted          => some .measured
  | .measured        => some .compiled
  | .compiled        => some .inferred
  | .inferred        => none

/-- The immediate predecessor of a stage, or `none` for the foundational
`.fact`. Inverse of `Stage.next` on its image. -/
def prev : Stage → Option Stage
  | .fact            => none
  | .distinguishable => some .fact
  | .admissible      => some .distinguishable
  | .countable       => some .admissible
  | .encoded         => some .countable
  | .residue         => some .encoded
  | .binary          => some .residue
  | .repeatable      => some .binary
  | .numeric         => some .repeatable
  | .representable   => some .numeric
  | .physical        => some .representable
  | .comparable      => some .physical
  | .observed        => some .comparable
  | .present         => some .observed
  | .measurable      => some .present
  | .gungan          => some .measurable
  | .source          => some .gungan
  | .executed        => some .source
  | .value           => some .executed
  | .magnitude       => some .value
  | .scaled          => some .magnitude
  | .load            => some .scaled
  | .finiteElephant  => some .load
  | .bullshit        => some .finiteElephant
  | .propaganda      => some .bullshit
  | .acolyte         => some .propaganda
  | .scientific      => some .acolyte
  | .truth           => some .scientific
  | .witnessed       => some .truth
  | .real            => some .witnessed
  | .«local»         => some .real
  | .universal       => some .«local»
  | .logical         => some .universal
  | .halted          => some .logical
  | .measured        => some .halted
  | .compiled        => some .measured
  | .inferred        => some .compiled

/-- Linear rank of a stage along the serial chain: `.fact` has rank 0,
`.inferred` has rank 36. The rank function makes "passes through the
predecessor" provable as `rank t = rank s + 1`. -/
def rank : Stage → Nat
  | .fact            => 0
  | .distinguishable => 1
  | .admissible      => 2
  | .countable       => 3
  | .encoded         => 4
  | .residue         => 5
  | .binary          => 6
  | .repeatable      => 7
  | .numeric         => 8
  | .representable   => 9
  | .physical        => 10
  | .comparable      => 11
  | .observed        => 12
  | .present         => 13
  | .measurable      => 14
  | .gungan          => 15
  | .source          => 16
  | .executed        => 17
  | .value           => 18
  | .magnitude       => 19
  | .scaled          => 20
  | .load            => 21
  | .finiteElephant  => 22
  | .bullshit        => 23
  | .propaganda      => 24
  | .acolyte         => 25
  | .scientific      => 26
  | .truth           => 27
  | .witnessed       => 28
  | .real            => 29
  | .«local»         => 30
  | .universal       => 31
  | .logical         => 32
  | .halted          => 33
  | .measured        => 34
  | .compiled        => 35
  | .inferred        => 36

/-- The rank function is injective on `Stage`: distinct stages have distinct
ranks. Verified by exhaustive case analysis (37 × 37 = 1369 cases, each
decidable). -/
theorem rank_injective : ∀ {a b : Stage}, Stage.rank a = Stage.rank b → a = b := by
  intro a b h
  cases a <;> cases b <;> simp_all [Stage.rank]

/-- Every stage's rank is at most `.inferred`'s rank (which is 36). -/
theorem rank_le_inferred (s : Stage) : Stage.rank s ≤ Stage.rank .inferred := by
  cases s <;> decide

end Stage

/-! ## The bundled cascade object -/

/-- A bundled record: a value type, its carrier, and evidence that all 36
gates are satisfied. Universe-polymorphic in `i`, matching the cascade
classes' `Value : Type i` signature. -/
structure FullCascadeObject where
  Value : Type i
  carrier : CarrierProcess Value
  [distinguishable_inst : DISTINGUISHABLE Value carrier]
  [admissible_inst : ADMISSIBLE Value carrier]
  [countable_inst : COUNTABLE Value carrier]
  [encoded_inst : ENCODED Value carrier]
  [residue_inst : RESIDUE Value carrier]
  [binary_inst : BINARY Value carrier]
  [repeatable_inst : REPEATABLE Value carrier]
  [numeric_inst : NUMERIC Value carrier]
  [representable_inst : REPRESENTABLE Value carrier]
  [physical_inst : PHYSICAL Value carrier]
  [comparable_inst : COMPARABLE Value carrier]
  [observed_inst : OBSERVED Value carrier]
  [present_inst : PRESENT Value carrier]
  [measurable_inst : MEASURABLE Value carrier]
  [gungan_inst : GUNGAN Value carrier]
  [source_inst : SOURCE Value carrier]
  [executed_inst : EXECUTED Value carrier]
  [value_inst : VALUE Value carrier]
  [magnitude_inst : MAGNITUDE Value carrier]
  [scaled_inst : SCALED Value carrier]
  [load_inst : LOAD Value carrier]
  [finiteElephant_inst : FINITE_ELEPHANT Value carrier]
  [bullshit_inst : BULLSHIT Value carrier]
  [propaganda_inst : PROPAGANDA Value carrier]
  [acolyte_inst : ACOLYTE Value carrier]
  [scientific_inst : SCIENTIFIC Value carrier]
  [truth_inst : TRUTH Value carrier]
  [witnessed_inst : WITNESSED Value carrier]
  [real_inst : REAL Value carrier]
  [local_inst : LOCAL Value carrier real_inst]   -- CHOICE(instrument 0a repair): sacred LOCAL ends with explicit (real: REAL); pass the cascade's REAL field. Canonical truth cascade has one REAL (real=imaginary, the δ¹=0 stationary blank).
  [universal_inst : UNIVERSAL Value carrier]
  [logical_inst : LOGICAL Value carrier]
  [halted_inst : HALTED Value carrier]
  [measured_inst : MEASURED Value carrier real_inst]   -- CHOICE(instrument 0a repair): sacred MEASURED has explicit (imaginary: REAL); pass real_inst (real=imaginary in the truth cascade).
  [compiled_inst : COMPILED Value carrier]
  [inferred_inst : INFERRED Value carrier]

/-! ## The canonical truth cascade -/

/-- The canonical realized cascade: `Prop` with `truthCarrier`, all 36
cascade instances chained as defined in `Episode16.lean`. -/
noncomputable def truthObject : FullCascadeObject where
  Value := Prop
  carrier := truthCarrier

end Measurement.Formalization
