import Measurement.Formalization.Grammar

/-!
# Herbrand: the generated symbolic universe

The Herbrand universe is the symbolic universe generated by the serial
grammar — NOT a Boolean profile space. A Herbrand term is a derivation
viewed as a syntactic object: an element of the closure of the productions
starting from `.fact`.

For the strictly serial grammar (one production per stage), `HTerm` is
isomorphic to `Derivation`. The distinction becomes meaningful when
alternate productions are added at any stage — each alternate generates a
new term. In the current setup there is exactly one canonical term per
stage and one canonical object per stage.

## Contents

- `HTerm s` — symbolic Herbrand term at stage `s`. Isomorphic to
  `Derivation s` in the strictly serial case.
- `HObject` — Sigma type collecting a stage and its term.
- `inferredTerm` / `inferredObject` — the canonical realized term and
  object at the terminal stage.

## Why this matters

Search through the Herbrand universe is search through serially generated
terms. The cascade sorts that search by cost. Without the serial grammar,
the raw term-growth explodes; with the cascade, it stays tractable. This
file isolates the term generation; `Cost.lean` provides the order;
`Irredundance.lean` argues that no production can be removed without losing
something the search needs.
-/

namespace Measurement.Formalization

/-- A symbolic term in the Herbrand universe at stage `s`. Defined by
exactly the same productions as `Derivation`; in the strictly serial
grammar `HTerm s ≃ Derivation s`. -/
inductive HTerm : Stage → Type
  | fact : HTerm .fact
  | app {s t : Stage} : Step s t → HTerm s → HTerm t

/-- A Herbrand object: a stage together with a term at that stage. -/
structure HObject where
  stage : Stage
  term : HTerm stage

namespace HTerm

/-- Convert a derivation into its Herbrand term form. -/
def ofDerivation {s : Stage} : Derivation s → HTerm s
  | .fact      => .fact
  | .step h d  => .app h (ofDerivation d)

/-- The size of a Herbrand term mirrors the length of its derivation. -/
def size {s : Stage} : HTerm s → Nat
  | .fact      => 0
  | .app _ t   => t.size + 1

end HTerm

/-- The canonical Herbrand term at `.inferred`. -/
def inferredTerm : HTerm .inferred :=
  HTerm.ofDerivation derivation_inferred

/-- The canonical Herbrand object at the terminal stage. -/
def inferredObject : HObject where
  stage := .inferred
  term := inferredTerm

end Measurement.Formalization
