import Measurement.Formalization.Herbrand

set_option autoImplicit false

/-!
# Terminal Uniqueness

The Herbrand universe generated by the serial grammar is subsingleton at every
stage. Combined with proof irrelevance of `Step` (which is `Prop`) and
structural induction on `HTerm`, every stage has at most one inhabitant; the
canonical `inferredTerm` then witnesses that the terminal stage has exactly
one inhabitant.

This file is the formal backbone for the QED bridge: an arbitrary interpreter
applied to any two terminal Herbrand terms agrees, because the terms
themselves are equal. The file also exposes the terminal-layer
`Nonempty` / `Subsingleton` / `OnePoint` observable-image carriers as
source surfaces that the later Bridge and QED image theorems mirror;
these terminal carriers are not themselves Bridge/QED image theorems.

## Contents

- `no_step_to_fact` — no `Step` lands at `.fact` (base-case helper).
- `step_source_unique` — same target uniquely determines source.
- `step_proof_irrel` — two proofs of `Step s t` are equal by proof irrelevance
  for propositions (named helper isolating the swap-site).
- `hterm_fact_unique` — every `HTerm .fact` is the canonical `.fact`.
- `hterm_eq` — main subsingleton result via structural induction.
- `hterm_subsingleton` — typeclass instance wrapping `hterm_eq`.
- `terminal_hterm_eq` — terminal-stage specialization.
- `hterm_inferred_eq_inferredTerm` — every terminal term equals the canonical.
- `terminal_hterm_unique` — `OnePoint (HTerm .inferred)` package combining
  Subsingleton with the canonical witness `inferredTerm` (this project
  imports no mathlib; `OnePoint` is the local stand-in for `Unique`).
- `terminal_observable_unique` — pairwise observable uniqueness.
- `terminal_observable_eq_inferredTerm` — canonical normal-form observable
  theorem against `inferredTerm`.
- `terminal_observable_image_nonempty` — the terminal-layer base
  Nonempty image existence surface; the observable image subtype is
  `Nonempty` with the witness supplied internally and canonically by
  `inferredTerm`. Mirrored later by the direct Bridge and QED
  image-nonempty theorems, which add an external encodability
  hypothesis that this terminal-layer theorem does not need.
- `terminal_observable_image_unique` — the terminal-layer source
  `OnePoint` observable-image surface; the image of terminal Herbrand
  terms under any interpreter carries a `OnePoint` package with default
  point `interpret inferredTerm`. Mirrored later by the direct Bridge and
  QED image-`OnePoint` surfaces, but this is not itself a Bridge/QED
  image theorem -- it is the source the later surfaces consume.
- `terminal_observable_image_subsingleton` — the terminal-layer
  `Subsingleton` observable-image carrier; the observable image
  subtype is `Subsingleton`, derived from
  `terminal_observable_image_unique` by routing both inhabitants
  through the `OnePoint` package's `uniq` field directly. Matches the
  later Bridge/QED `*_image_subsingleton` naming pattern, but is not
  itself a Bridge/QED image theorem -- it is the terminal-layer
  carrier the later surfaces mirror.

## No new axioms

The proof uses only the existing `Step.unique`, `Step.prev_eq`,
`Step.target_rank_pos`, and `Stage.rank` machinery from `Grammar.lean` and
`Epiphany.lean`. No new axioms; no `sorry`; no `noncomputable`.
-/

namespace Measurement.Formalization

universe u

/-! ## Base-case helper -/

/-- No `Step` lands at `.fact`. The serial chain starts at `.fact`; nothing
precedes it.

Proved via `Step.target_rank_pos` plus the definitional fact
`Stage.rank .fact = 0`. -/
theorem no_step_to_fact (s : Stage) : ¬ Step s .fact := by
  intro h
  have hpos : 0 < Stage.rank .fact := Step.target_rank_pos h
  simp [Stage.rank] at hpos

/-! ## Source determinism of a step -/

/-- Two `Step`s with the same target have the same source.

This is the converse of `Step.unique`: that says the target is determined by
the source; this says the source is determined by the target. Proved via
`Step.prev_eq` plus injectivity of `Option.some`. -/
theorem step_source_unique {s₁ s₂ t : Stage}
    (h₁ : Step s₁ t) (h₂ : Step s₂ t) : s₁ = s₂ := by
  have e₁ := Step.prev_eq h₁
  have e₂ := Step.prev_eq h₂
  rw [e₁] at e₂
  exact Option.some.inj e₂

/-! ## Proof irrelevance for `Step`

`Step s t` is a proposition, so any two proofs of it are equal by proof
irrelevance for propositions. The named lemma exposes that fact in one place;
if elaboration later rejects this spelling, the replacement belongs here and
not inside `hterm_eq`. -/

/-- Two proofs of `Step s t` are equal by proof irrelevance for propositions.

`Step s t` unfolds to `Stage.next s = some t`, which is in `Prop`. Lean's
`Subsingleton.elim` discharges the equality through typeclass synthesis on
`Subsingleton`. If a future elaboration rejects this spelling, change only
the right-hand side of this lemma; the use site in `hterm_eq` stays the
same. -/
theorem step_proof_irrel {s t : Stage} (h₁ h₂ : Step s t) : h₁ = h₂ :=
  Subsingleton.elim h₁ h₂

/-! ## The Herbrand universe is subsingleton at every stage -/

/-- Every `HTerm .fact` is the canonical `.fact` constructor.

The only other constructor `.app h _` would require `h : Step _ .fact`, ruled
out by `no_step_to_fact`. -/
theorem hterm_fact_unique (t : HTerm .fact) : t = .fact := by
  cases t with
  | fact => rfl
  | app h _ => exact absurd h (no_step_to_fact _)

/-- Any two Herbrand terms at the same stage are equal.

Proof by structural induction on the first term:
- base: a `.fact` term is determined via `hterm_fact_unique`.
- step: an `.app h₁ u₁` term equals an `.app h₂ u₂` after
    (1) reconciling the source via `step_source_unique`,
    (2) the sub-terms via the induction hypothesis,
    (3) the `Step` proofs by proof irrelevance for propositions. -/
theorem hterm_eq : ∀ {s : Stage} (t₁ t₂ : HTerm s), t₁ = t₂ := by
  intro s t₁
  induction t₁ with
  | fact =>
      intro t₂
      exact (hterm_fact_unique t₂).symm
  | @app s' t h₁ u₁ ih =>
      intro t₂
      cases t₂ with
      | fact => exact absurd h₁ (no_step_to_fact _)
      | app h₂ u₂ =>
          have hs := step_source_unique h₁ h₂
          subst hs
          have hu := ih u₂
          subst hu
          -- After both substs: goal is `HTerm.app h₁ u₁ = HTerm.app h₂ u₁`.
          -- `h₁ h₂ : Step s' t` are two proofs of the same `Prop`, equal by
          -- proof irrelevance. The named helper `step_proof_irrel` isolates
          -- the proof-irrelevance step so any future fallback lives in
          -- exactly one place.
          rw [step_proof_irrel h₁ h₂]

/-- Subsingleton instance wrapping `hterm_eq`. Enables `Subsingleton.elim`
on any `HTerm s` automatically. -/
instance hterm_subsingleton {s : Stage} : Subsingleton (HTerm s) :=
  ⟨hterm_eq⟩

/-! ## Specializations at the terminal stage -/

/-- Specialization of `hterm_eq` at the terminal stage `.inferred`. -/
theorem terminal_hterm_eq (t₁ t₂ : HTerm .inferred) : t₁ = t₂ :=
  hterm_eq t₁ t₂

/-- Every Herbrand term at `.inferred` is the canonical `inferredTerm`. -/
theorem hterm_inferred_eq_inferredTerm (t : HTerm .inferred) :
    t = inferredTerm :=
  hterm_eq t inferredTerm

/-- Local one-point package: a default inhabitant together with the proof
that every inhabitant equals it. This project imports no mathlib, so the
standard `Unique` class is unavailable; `OnePoint` carries the same two
fields and is used consistently across the terminal, Bridge, and QED
layers. -/
structure OnePoint (α : Sort u) where
  default : α
  uniq : ∀ x : α, x = default

/-- The terminal Herbrand type has exactly one inhabitant, witnessed by
`inferredTerm`. Combining `hterm_subsingleton` (Subsingleton from `hterm_eq`)
with the existence of `inferredTerm` (the canonical derivation reaching the
terminal stage) gives the local `OnePoint` package. Downstream bridge code
that wants "inhabited plus subsingleton" reads it through this single
definition. -/
def terminal_hterm_unique : OnePoint (HTerm .inferred) where
  default := inferredTerm
  uniq := hterm_inferred_eq_inferredTerm

instance terminal_hterm_inhabited : Inhabited (HTerm .inferred) :=
  ⟨inferredTerm⟩

/-! ## Observable uniqueness

The QED bridge's first half: under any interpreter, two terminal Herbrand
terms produce the same observable, because the terms themselves are equal.
This avoids any reasoning about proof identity of `Derivation .inferred`. -/

/-- The interpretation of any two terminal Herbrand terms is the same. -/
theorem terminal_observable_unique
    {α : Type u}
    (interpret : HTerm .inferred → α)
    (t₁ t₂ : HTerm .inferred) :
    interpret t₁ = interpret t₂ := by
  rw [hterm_eq t₁ t₂]

/-- Any terminal Herbrand term has the same interpreted value as the
canonical `inferredTerm`. This is the normal-form reading of terminal
observable uniqueness: every interpretation reduces to the canonical
terminal witness. Useful as a downstream rewriting anchor and as the
prose form of "one terminal value." -/
theorem terminal_observable_eq_inferredTerm
    {α : Type u}
    (interpret : HTerm .inferred → α)
    (t : HTerm .inferred) :
    interpret t = interpret inferredTerm := by
  rw [hterm_inferred_eq_inferredTerm t]

/-- The image of terminal Herbrand terms under any interpreter is
`Nonempty`, inhabited by `⟨interpret inferredTerm, ⟨inferredTerm,
rfl⟩⟩`. The terminal-layer base Nonempty existence surface, mirrored
later by the direct Bridge `fge_observable_image_nonempty_under_encoding`
and its abstract QED + via-QED analogs.

The conclusion is about the terminal observable-image subtype (terms
in `HTerm .inferred` paired with their interpreted values), not raw
observable values and not any external candidates. The witness is
supplied internally by `inferredTerm`; the terminal layer has no
external `hx` / `ha` / `ea` hypothesis, because `inferredTerm` is
already available as the canonical terminal term. The theorem adds
no uniqueness claim by itself and needs no `Subsingleton` instance or
routing for the proof, which is one anonymous-constructor pair;
it merely exposes the weaker `Nonempty` carrier as a companion to
`terminal_observable_image_unique`. Useful when a downstream caller
wants `Nonempty` without committing to the full `Unique` instance,
e.g. for `Nonempty.elim` or `Classical.choice`-style reasoning. -/
theorem terminal_observable_image_nonempty
    {α : Type u}
    (interpret : HTerm .inferred → α) :
    Nonempty
      { a : α //
        ∃ t : HTerm .inferred,
          a = interpret t } :=
  ⟨⟨interpret inferredTerm, ⟨inferredTerm, rfl⟩⟩⟩

/-- The image of terminal Herbrand terms under any interpreter is
`Unique`, with the canonical default `interpret inferredTerm`.
Terminal-level analog of the Bridge and QED nonempty image `Unique`
theorems (`fge_observable_image_unique_under_encoding` and
`device_gauge_image_unique`); the proof here needs no nonempty
hypothesis because `inferredTerm` is always available as the canonical
witness.

Concretely:

- `default` is `⟨interpret inferredTerm, ⟨inferredTerm, rfl⟩⟩`;
- `uniq` routes each subtype inhabitant through
  `terminal_observable_eq_inferredTerm`, lifted to the subtype via
  `Subtype.ext`.

This is NOT a Bridge or QED image theorem. The subtype here is the
terminal-level observable image (terms in `HTerm .inferred` paired
with their interpreted values), without any encoding or admissibility
predicate; downstream layers add those predicates and inherit the
image-uniqueness pattern. The theorem only says the terminal
observable image has a canonical point. -/
def terminal_observable_image_unique
    {α : Type u}
    (interpret : HTerm .inferred → α) :
    OnePoint
      { a : α //
        ∃ t : HTerm .inferred,
          a = interpret t } := by
  refine
    { default := ⟨interpret inferredTerm, ⟨inferredTerm, rfl⟩⟩,
      uniq := ?_ }
  intro o
  rcases o with ⟨v, hv⟩
  rcases hv with ⟨t, rfl⟩
  exact Subtype.ext (terminal_observable_eq_inferredTerm interpret t)

/-- The image of terminal Herbrand terms under any interpreter is a
`Subsingleton`. This is the terminal-layer companion to
`terminal_observable_image_unique`, matching the Bridge/QED
`*_image_subsingleton` naming pattern. The proof routes both inhabitants
through the `OnePoint` package's `uniq` field directly -- no mathlib
`Unique → Subsingleton` inference path is available or needed. -/
theorem terminal_observable_image_subsingleton
    {α : Type u}
    (interpret : HTerm .inferred → α) :
    Subsingleton
      { a : α //
        ∃ t : HTerm .inferred,
          a = interpret t } := by
  constructor
  intro x y
  rw [(terminal_observable_image_unique interpret).uniq x,
    (terminal_observable_image_unique interpret).uniq y]

end Measurement.Formalization
